apiVersion: v1
kind: Secret
metadata:
  name: {{ include "realtime-docs.fullname" . }}-config
  labels:
    {{- include "realtime-docs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc }}
  {{- else }}
  database-url: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=require" .Values.externalDatabase.username .Values.secrets.dbPassword .Values.externalDatabase.host (.Values.externalDatabase.port | toString) .Values.externalDatabase.database | b64enc }}
  {{- end }}
  {{- if .Values.secrets.redisAddr }}
  redis-addr: {{ .Values.secrets.redisAddr | b64enc }}
  {{- else }}
  redis-addr: {{ printf "%s:%s" .Values.externalRedis.host (.Values.externalRedis.port | toString) | b64enc }}
  {{- end }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
